import express from 'express';
import { getStore, saveStore } from '../config/store.js';
import { authMiddleware } from '../middleware/auth.js';
import { createMeetingRoom } from '../services/meetingService.js';
import { generateSessionPlan } from '../services/aiService.js';
import { sendEmail, emailTemplates } from '../services/emailService.js';

const router = express.Router();

// List sessions for logged-in user
router.get('/', authMiddleware, (req, res) => {
  const store = getStore();
  const userSessions = store.sessions.filter(
    s => s.mentorId === req.user.id || s.learnerId === req.user.id
  );
  res.json({ sessions: userSessions });
});

// Get session by ID
router.get('/:id', authMiddleware, (req, res) => {
  const store = getStore();
  const session = store.sessions.find(s => s.id === req.params.id);
  if (!session) return res.status(404).json({ message: 'Session not found' });
  res.json({ session });
});

// Schedule Learning Session
router.post('/', authMiddleware, async (req, res) => {
  try {
    const { partnerId, skill, topic, date, time, durationMinutes = 60, mode = 'online', role = 'mentor' } = req.body;
    const store = getStore();

    if (!partnerId || !skill || !topic || !date || !time) {
      return res.status(400).json({ message: 'Partner ID, skill, topic, date, and time are required.' });
    }

    const partner = store.users.find(u => u.id === partnerId);
    const currentUser = store.users.find(u => u.id === req.user.id);
    if (!partner) return res.status(404).json({ message: 'Partner not found.' });

    const isCurrentUserMentor = role === 'mentor';
    const mentor = isCurrentUserMentor ? currentUser : partner;
    const learner = isCurrentUserMentor ? partner : currentUser;

    // Meeting link generation (Google Meet or SkillMate Demo Meeting Room)
    let meetingLink = '';
    let isDemoMeeting = false;

    if (mode === 'online') {
      const room = await createMeetingRoom({
        title: `${skill} - ${topic}`,
        date,
        time,
        durationMinutes,
        mentor,
        learner
      });
      meetingLink = room.meetingLink;
      isDemoMeeting = room.isDemo;
    }

    // AI Generated Suggested Session Plan
    const agenda = await generateSessionPlan({
      skill,
      topic,
      level: 'Intermediate',
      durationMinutes
    });

    const newSession = {
      id: 'sess_' + Date.now(),
      mentorId: mentor.id,
      mentorName: mentor.name,
      mentorAvatar: mentor.avatar,
      learnerId: learner.id,
      learnerName: learner.name,
      learnerAvatar: learner.avatar,
      skill,
      topic,
      date,
      time,
      durationMinutes: parseInt(durationMinutes),
      mode,
      meetingLink,
      isDemoMeeting,
      status: 'scheduled',
      agenda,
      notes: `Scheduled via SkillMate. Session agenda generated by AI.`,
      createdAt: new Date().toISOString()
    };

    store.sessions.push(newSession);

    // Notifications for both
    const notifMessage = `Session scheduled: ${topic} on ${date} at ${time} (${mode === 'online' ? (isDemoMeeting ? 'Demo Meeting Room' : 'Google Meet') : 'Offline'}).`;
    
    store.notifications.push({
      id: 'notif_' + Date.now() + '_1',
      userId: partner.id,
      title: '📅 New Session Scheduled',
      message: `${currentUser.name} scheduled a session with you: ${topic}.`,
      type: 'session_scheduled',
      read: false,
      actionLink: '/sessions',
      createdAt: new Date().toISOString()
    });

    store.notifications.push({
      id: 'notif_' + Date.now() + '_2',
      userId: currentUser.id,
      title: '📅 Session Confirmed',
      message: notifMessage,
      type: 'session_scheduled',
      read: false,
      actionLink: '/sessions',
      createdAt: new Date().toISOString()
    });

    saveStore();

    // Trigger emails to both participants
    try {
      const template = emailTemplates.sessionScheduled(topic, date, time, meetingLink, isDemoMeeting);
      sendEmail({ to: mentor.email, subject: template.subject, html: template.html, category: 'Session' });
      sendEmail({ to: learner.email, subject: template.subject, html: template.html, category: 'Session' });
    } catch (mailErr) {
      console.warn('Session schedule email warning:', mailErr.message);
    }

    res.status(201).json({
      message: 'Session successfully scheduled! Meeting link and AI plan generated.',
      session: newSession
    });
  } catch (err) {
    res.status(500).json({ message: 'Error scheduling session', error: err.message });
  }
});

// Update / Complete Session
router.put('/:id', authMiddleware, (req, res) => {
  try {
    const { status, notes } = req.body; // 'completed' | 'cancelled' | 'in_progress'
    const store = getStore();

    const session = store.sessions.find(s => s.id === req.params.id);
    if (!session) return res.status(404).json({ message: 'Session not found' });

    if (session.mentorId !== req.user.id && session.learnerId !== req.user.id) {
      return res.status(403).json({ message: 'Unauthorized.' });
    }

    const previousStatus = session.status;
    if (status) session.status = status;
    if (notes) session.notes = notes;
    session.updatedAt = new Date().toISOString();

    // If transitioned to completed:
    if (status === 'completed' && previousStatus !== 'completed') {
      const mentor = store.users.find(u => u.id === session.mentorId);
      const learner = store.users.find(u => u.id === session.learnerId);

      // Mentor receives +20 Skill Credits
      if (mentor) {
        mentor.skillCredits = (mentor.skillCredits || 100) + 20;
        mentor.teachingHours = (mentor.teachingHours || 0) + (session.durationMinutes / 60);

        store.credits.push({
          id: 'tx_' + Date.now() + '_m',
          userId: mentor.id,
          amount: 20,
          type: 'teaching_session',
          description: `🎓 Completed teaching session: ${session.topic}`,
          balanceAfter: mentor.skillCredits,
          createdAt: new Date().toISOString()
        });
      }

      // Learner spends / balances -20 credits and logs learning hours
      if (learner) {
        learner.skillCredits = Math.max(0, (learner.skillCredits || 100) - 20);
        learner.learningHours = (learner.learningHours || 0) + (session.durationMinutes / 60);

        store.credits.push({
          id: 'tx_' + Date.now() + '_l',
          userId: learner.id,
          amount: -20,
          type: 'learning_session',
          description: `📚 Attended peer learning session: ${session.topic}`,
          balanceAfter: learner.skillCredits,
          createdAt: new Date().toISOString()
        });
      }

      // Notifications
      store.notifications.push({
        id: 'notif_' + Date.now() + '_comp',
        userId: session.learnerId,
        title: '⭐ Rate Your Learning Session',
        message: `Your session on "${session.topic}" with ${session.mentorName} is complete. Please rate your mentor!`,
        type: 'rating_received',
        read: false,
        actionLink: '/sessions',
        createdAt: new Date().toISOString()
      });
    }

    saveStore();
    res.json({ message: `Session status updated to ${status}!`, session });
  } catch (err) {
    res.status(500).json({ message: 'Error updating session', error: err.message });
  }
});

export default router;
